# Generated by Django 5.2.7 on 2025-11-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('next_index', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVEHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cveId', models.CharField(db_index=True, max_length=200)),
                ('eventName', models.CharField(blank=True, max_length=200, null=True)),
                ('cveChangeId', models.CharField(db_index=True, max_length=200, unique=True)),
                ('sourceIdentifier', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cveId'], name='cve_records_cveId_91ca02_idx'), models.Index(fields=['cveChangeId'], name='cve_records_cveChan_0560eb_idx'), models.Index(fields=['created', 'id'], name='cve_records_created_429b03_idx'), models.Index(fields=['eventName', 'id'], name='cve_records_eventNa_7f0415_idx'), models.Index(fields=['sourceIdentifier', 'id'], name='cve_records_sourceI_1b998e_idx')],
            },
        ),
    ]
