# Generated by Django 5.2.7 on 2025-11-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cvehistory',
            name='cve_records_cveId_91ca02_idx',
        ),
        migrations.RemoveIndex(
            model_name='cvehistory',
            name='cve_records_cveChan_0560eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='cvehistory',
            name='cve_records_created_429b03_idx',
        ),
        migrations.RemoveIndex(
            model_name='cvehistory',
            name='cve_records_eventNa_7f0415_idx',
        ),
        migrations.RemoveIndex(
            model_name='cvehistory',
            name='cve_records_sourceI_1b998e_idx',
        ),
        migrations.AlterField(
            model_name='cvehistory',
            name='cveChangeId',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cvehistory',
            name='cveId',
            field=models.CharField(max_length=200),
        ),
    ]
