# Generated by Django 5.2.7 on 2025-11-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_records', '0002_remove_cvehistory_cve_records_cveid_91ca02_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvehistory',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cvehistory',
            name='cveId',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cvehistory',
            name='eventName',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cvehistory',
            name='sourceIdentifier',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
